### ISSUE TITLE
The Gitpod Error That I Found.

### ISSUE THREAD

**Issue by WeakJames1** [AUPE-Programmers/Homework#2]
gitpod /workspace/WeakJames1 $ cd '/workspace/WeakJames1' && env '/home/gitpod/.sdkman/candidates/java/current/bin/java' '-Dfile.encoding=UTF-8' '-cp' '/home/gitpod/.theia/workspace-storage/88878a18a41576200d2b066792671dc8/redhat.java/jdt_ws/WeakJames1_bec6558e/bin' 'ProgrammerCreed'
Picked up JAVA_TOOL_OPTIONS: -Xmx2254m
Error: Could not find or load main class ProgrammerCreed
Caused by: java.lang.ClassNotFoundException: ProgrammerCreed

**Comment by lawrenberg** [comment]
Hi James,

Can you provide a screenshot?  Let me know if you need assistance on how to make a screenshot.

**Comment by WeakJames1** [comment]
![2020-07-11 (5)](https://user-images.githubusercontent.com/68130410/87235395-be6e2400-c3a9-11ea-80dc-237979d2570c.png)

**Comment by lawrenberg** [comment]
You need to save first before you can run it.

**Comment by lawrenberg** [comment]
The white dot in the tab means you need to save

**Comment by GodSpeed175** [comment]
I have also found the error in git pod

.encoding=UTF-8' '-cp' '/home/gitpod/.theia/workspace-storage/122974ee6e4f5f6f2510a9b608faf067/redhat.java/jdt_ws/JesusAgosto_47f747f2/bin' 'ProgrammerCreed'
Picked up JAVA_TOOL_OPTIONS: -Xmx2254m
Error: Could not find or load main class ProgrammerCreed
Caused by: java.lang.ClassNotFoundException: ProgrammerCreed

**Comment by lawrenberg** [comment]
@GodSpeed175 did you save the file first?

**Comment by lawrenberg** [comment]
So when you see "Could not find or load main class". So there are 2 reasons you maybe be getting this:

1) You didn't save your file first, so the compiler sees an empty file

Solution: save your file first before you run
2) The class is named differently from the file name.  For example,
ProgrammerCreed.java (file name) but you class is name Orange " class Orange".
Solution:  make sure the class and file name are named the same. Also check for misspellings.
