### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by GodSpeed175** [AUPE-Programmers/Homework#6]
Hi Ms Lawren, sorry for commenting this late. I am now confused because i was doing exercise 2, everything was going great but something weird happened. Both my folder and my file had a "M" which means Modified. Me and James were helping each other out and when i got to the 4th line in exercise 2 something happen. It wouldn't run. I saved it, went back to the home screen of Gitpod went back to my saved file and it showed me the "M" and for James its a U (unstaged). I am right now stuck.

**Comment by lawrenberg** [comment]
First I would like to say great job collaborating, @GodSpeed175 and @WeakJames1.  To better help you guys, please provide a screenshot of your work in Gitpod.

**Comment by GodSpeed175** [comment]
How do I do screenshot and send it to you in the issue section?

**Comment by lawrenberg** [comment]
To do a screenshot, press 'print screen' (this button is found at the very first row of your keyboard where the function keys are - F1 button, F2 button, etc.  The print screen button may be spelled in different ways depending on your keyboard just as 'prtsc' or 'print scr', etc.  If you see a button that shares a lot of the letters the words and has a similar sequence of letters, then it is most likely the 'Print Screen' button).  If you see that the word "Print Screen" (or similar) is above another word, then you have to hold the "FN" button and press the "Print Screen" (or similar) button down once, then let go of all the keys.

You will see a flash on the screen and/or a sound like a camera, and that means the computer took a picture of the screen.

Find the image on your computer - normally it is in the Picture folder.  Then Drag-and-drop the image into your reply to the Issue.

**Comment by lawrenberg** [comment]
@GodSpeed175 and @WeakJames1 were you able to figure out your issue?

**Comment by GodSpeed175** [comment]
![2020-07-23](https://user-images.githubusercontent.com/67125132/88329756-7085e400-ccf8-11ea-853e-3ed679b9c09a.png)

**Comment by GodSpeed175** [comment]
I did not want to continue because maybe the same thing will happen again

**Comment by GodSpeed175** [comment]
I think the problem is that i did not did the pull request part, or maybe commit, or made a new repository.

**Comment by lawrenberg** [comment]
The problem is Line#6.  The red squiggle underneath the parenthesis tells you where the issue is.  If you place your mouse cursor over the red squiggle it tells you what is wrong.  So let's break it down what's wrong with Line#6 `System.out.println(())` :

1. You are missing a semicolon `;` after the  `System.out.println()` statement.
2. You have a () within the the `System.out.println()` statement.  Without an math or logic expression ( i.e. math expression 4+4 or logic expression: trueStatement && falseStatement ), the extra () services no purpose and is compiler doesn't understand what you are trying to say.

**Comment by GodSpeed175** [comment]
That part I know, i just didn't put the code such as ((int)1+4);. The thing i am comfuesd is where my folder and my file has a M and there is a red bar
![2020-07-23 (2)](https://user-images.githubusercontent.com/67125132/88332076-feaf9980-ccfb-11ea-97fa-cadb7f12649b.png)

**Comment by GodSpeed175** [comment]
Hello Ms Lawren, sorry for texting this late and also sorry for doing this a little late. I'm was almost done with exercise 2, i was at 7th equation but the thing is that my output wasnt showing up. I tried a lot of ways that might fix it but nothing work.

**Comment by GodSpeed175** [comment]
![2020-07-27](https://user-images.githubusercontent.com/67125132/88617206-ff319280-d063-11ea-9f3e-140e393a72f4.png)

**Comment by GodSpeed175** [comment]
![2020-07-27](https://user-images.githubusercontent.com/67125132/88617227-0eb0db80-d064-11ea-9c8e-b8a5c26e9247.png)

**Comment by GodSpeed175** [comment]
![2020-07-27 (2)](https://user-images.githubusercontent.com/67125132/88617261-27b98c80-d064-11ea-9ee0-7621dd71555a.png)

**Comment by GodSpeed175** [comment]
The p, q, and r are part of the last line of the system.out.println.

**Comment by lawrenberg** [comment]
@GodSpeed175 The last out did come out.  Why did you assume it didn't?

**Comment by Meleciel** [comment]
the git pod does not allow me to push

**Comment by lawrenberg** [comment]
What errors are you getting?

**Comment by Meleciel** [comment]
it says that i dont have permition to push

**Comment by lawrenberg** [comment]
I sent a reply in the original email you sent.
