### ISSUE TITLE
4th h.w

### ISSUE THREAD

**Issue by GodSpeed175** [AUPE-Programmers/Homework#9]
I fix the problem but not it wont run, it keeps showing me this.
![2020-08-04 (18)](https://user-images.githubusercontent.com/67125132/89358304-fb6bc480-d690-11ea-8ef7-8c10b6b22091.png)

**Comment by lawrenberg** [comment]
Click "Fix" and select the first option.  See if that works

**Comment by GodSpeed175** [comment]
![2020-08-04 (23)](https://user-images.githubusercontent.com/67125132/89363217-a8e4d500-d69d-11ea-9403-399e4701c386.png)

**Comment by GodSpeed175** [comment]
![2020-08-04 (24)](https://user-images.githubusercontent.com/67125132/89363256-bbf7a500-d69d-11ea-915b-598415cc274b.png)

**Comment by lawrenberg** [comment]
You have to set up a command-line app.  Please refer to https://github.com/AUPE-Programmers/Homework/blob/master/Homework_2.md#exercise-1---creating-a-command-line-app

**Comment by GodSpeed175** [comment]
I got my output, do i still need to put the command line app even though I have all of my answers?

**Comment by lawrenberg** [comment]
The output you received wasn't from the Group_Two.java.  It is from LogicPractice.

**Comment by GodSpeed175** [comment]
I created different folders and files that is linked to the Homework4 folder

**Comment by GodSpeed175** [comment]
![2020-08-04 (25)](https://user-images.githubusercontent.com/67125132/89368622-fc5d2000-d6a9-11ea-8458-f19c6426edb3.png)

**Comment by GodSpeed175** [comment]
And I still have the correct outputs.

**Comment by GodSpeed175** [comment]
Or I was supposed to create different files that are linked to the same folder?

**Comment by lawrenberg** [comment]
how you choose to organize it is up to you.
By the way if you want to confirm which output belongs to which file:
![godspeed_screenshot](https://user-images.githubusercontent.com/391150/89368935-b6ed2280-d6aa-11ea-9a98-42ae7c07747e.png)
